### ISSUE TITLE
Can't complete setup

### ISSUE THREAD

**Issue by aibradford** [pbrink231/plex_top_playlists#15]
Receving this error: 

Retrieving a list of movies from the 'Movies' library in Plex...
Retrieving new lists
Retrieving the Trakt weekly list...
Retrieving the Trakt popular list...
Movies Top Weekly: finding matching movies for playlist with count 80
Traceback (most recent call last):
  File "plex_playlist_update.py", line 374, in <module>
    list_updater()
  File "plex_playlist_update.py", line 365, in list_updater
    run_movies_lists(plex)
  File "plex_playlist_update.py", line 298, in run_movies_lists
    setup_movie_playlist(plex, trakt_weekly_imdb_ids, all_movies, TRAKT_WEEKLY_PLAYLIST_NAME)
  File "plex_playlist_update.py", line 137, in setup_movie_playlist
    if movie.guid != NA and 'imdb://' in movie.guid:
NameError: global name 'NA' is not defined

How do i define it? Or how do i make it work? Any help please....im not much of a coder. Also, im using Windows 10.

**Comment by m-rots** [comment]
I'm having the same issue, have you found a solution yet? Thanks! 

Traceback (most recent call last):
  File "./plex_playlist_update.py", line 24, in <module>
    from plexapi.utils import NA
ImportError: cannot import name NA

On Ubuntu btw

**Comment by m-rots** [comment]
I've actually already fixed it, instead of using the normal PlexAPI use this one instead: https://github.com/Hellowlol/plexapi

**Comment by goku-son** [comment]
@notTeresa I already have the normal plexapi installed. May I ask how I go about installing the plexapi you cite? I initially installed plexapi by runnin pip install plexapi so just trying to figure out how to install the above version. Also, will loading that version break other items that replied on the original plexapi?

Traceback (most recent call last):
File "./plex_playlist_update.py", line 24, in 
from plexapi.utils import NA
ImportError: cannot import name NA

I am running on Windows if it matters.

**Comment by pbrink231** [comment]
This was a change in the python plexapi where they no longer had NA.  It has been resolved and should work fine now.
