### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by Mushin** [pbrink231/plex_top_playlists#16]
Is there any way to get this running on Windows?

**Comment by pbrink231** [comment]
Hey @Mushin.  Had an issue with my Plex before.  Have it all in docker now.  Going to get this thing up to par again in a couple weeks when I get some time.  Welcome to take a stab at it.

**Comment by goku-son** [comment]
I would also like to know if this will run on Windows.

**Comment by pbrink231** [comment]
This will run on Windows.  I have tested it now on Windows and working fully.
