### ISSUE TITLE
Support Managed Users

### ISSUE THREAD

**Issue by zhdenny** [pbrink231/plex_top_playlists#19]
Script supports Shared Users but not Managed Users.....any chance of adding this?

**Comment by pbrink231** [comment]
I personally have never set up a managed user.  Just finding out about them now.  Ill see what I can find on them.

**Comment by desimaniac** [comment]
I've been told this script is able to push to managed users as well: https://gist.github.com/JonnyWong16/2607abf0e3431b6f133861bbe1bb694e

**Comment by goku-son** [comment]
I would also like to see this for managed users if at all possible. Thanks!

**Comment by pbrink231** [comment]
Script now supports managed users
