### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by karthistark** [pbrink231/plex_top_playlists#21]
Traceback (most recent call last):
  File "plex_playlist_update.py", line 553, in <module>
    list_updater(plex)
  File "plex_playlist_update.py", line 514, in list_updater
    users = get_user_tokens(plex)
  File "plex_playlist_update.py", line 505, in get_user_tokens
    users = get_all_users(plex)
  File "plex_playlist_update.py", line 488, in get_all_users
    user_ids = {plex_user['@id']: plex_user.get('@username', plex_user.get('@title')) for plex_user in xmlData2['MediaContainer']['User']}
KeyError: 'User'

**Comment by pbrink231** [comment]
Can you go to a browser and put this url

https://plex.tv/api/users?X-Plex-Token={token}

Please replace {token} with the token you are using in your config file.

Copy and paste the xml here or paste into a word document and put it here.  you may want to black out the username and email addresses shown.   If you have several users you could probably remove a few so its not so long. 

My assumption is you don't have any users created yet.

**Comment by pbrink231** [comment]
d6fc438 should fix the issue.  Tested with a fresh plex account and recreated the issue.

**Comment by karthistark** [comment]
Hi,
Thanks for your reply and new modified code. It works now. One more request
from me. Can you write a code for creating text document which has missing
movies under each playlist. It helps me to download missing movies later.

Regards,
Karthik

**Comment by pbrink231** [comment]
Would it just be a file in the same location as the script?  Would you want a file per list or just a full summary file.  I am thinking a single file per playlist which would be overwritten next time it is run.

Also check out the discord which sends in a discord channel and gives you the same information.  I put instructions in the wiki.  very easy to do.  Also lets you get it from anywhere.

![discord_image](https://github.com/pbrink231/plex_top_playlists/wiki/images/discord-output.PNG)

**Comment by pbrink231** [comment]
Also mind making a new issue for this.

**Comment by karthistark** [comment]
Hi,
I want this script work with emby/ jellfin.
I really this script while using plex. Now i moved to emby. I searched
everywhere to find similar script. I couldnt find it.
Thanks in advance
