### ISSUE TITLE
Add option to convert playlist into collection

### ISSUE THREAD

**Issue by hbooo** [pbrink231/plex_top_playlists#24]
Hi, 

This script is very useful and I now have a lot of playlists imported thanks to this. But in my opinion playlists aren't the best approach for every movies/series.

First of all I can't hide items I have already seen in playlists, also items in the playlist are not so viewable with the list view.

As I don't think Plex will change this anytime soon it could be great if your script allows us to specify for each playlist if it needs to import this as a playlist (useful for timeline) or collection.

I hope this is technically possible, 

Thanks again for this great script

**Comment by pbrink231** [comment]
Thank you for the positive feedback.

Decided to take a stab at it.  The new version 2.00 (seen in the new version file) allows adding movies and tv shows (**disclaimer below**) to a collection.

I have updated the settings.ini.example to explain how its done.  basically just add "kind":"collection" to your lists and they will be made as a collection instead of a playlist.

**TV Shows Issue** - The plexapi does not have collections supported on shows.  I have submitted a pull request to fix this and when it is updated it will work.  Until then adding this to shows will fail.

https://github.com/pkkid/python-plexapi/pull/351

**Comment by pbrink231** [comment]
Also to note I have not added a remove function for collections.  Will add at another time.

**Comment by hbooo** [comment]
Thanks for the quick fix!

I got an error when I try to use the new script 
`Retrieving new lists
Studio Ghibli: STARTING PLAYLIST - TYPE: custom - URL: https://www.imdb.com/list/ls068907948/
Studio Ghibli: finding matching movies for playlist with count 42
Traceback (most recent call last):
File "/mnt/user/appdata/PlexLibrary/plex_top_playlists/plex_playlist_update.py", line 577, in 
list_updater(plex)
File "/mnt/user/appdata/PlexLibrary/plex_top_playlists/plex_playlist_update.py", line 542, in list_updater
run_movies_lists(plex, users)
File "/mnt/user/appdata/PlexLibrary/plex_top_playlists/plex_playlist_update.py", line 427, in run_movies_lists
imdb_list_loop(plex, shared_users, movie_id_dict)
File "/mnt/user/appdata/PlexLibrary/plex_top_playlists/plex_playlist_update.py", line 392, in imdb_list_loop
setup_movie_playlist(plex, shared_users, ids, movie_id_dict, title, kind)
File "/mnt/user/appdata/PlexLibrary/plex_top_playlists/plex_playlist_update.py", line 265, in setup_movie_playlist
add_items_to_collection(plex, summary.matching_movies, summary.name)
File "/mnt/user/appdata/PlexLibrary/plex_top_playlists/plex_playlist_update.py", line 248, in add_items_to_collection
print("Adding tag: {0}, To media: {1}".format(tag, media))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 55: ordinal not in range(128)`

And here is a part of the config file
`   { "title":"Studio Ghibli", "type":"custom", "url":"https://www.imdb.com/list/ls068907948/", "kind":"collection"},`

**Comment by pbrink231** [comment]
ok so I believe it was a movie title on a print that was giving the error
Nausicaä of the Valley of the Wind (1984)

ä is not an ASCII character.  This is good to know when I show movie titles in the log from radarr.  I just removed that print dialog and should fix it.

3e43dd5f123976fb6a0c45645237690ee86127c2 now version 2.01

**Comment by pbrink231** [comment]
https://github.com/pkkid/python-plexapi/pull/351 is the pull request waiting so collections can be added to shows

**Comment by pbrink231** [comment]
Ok updated the requirements to pull the plexapi master branch.
need to run

```
git pull
pip3 install -r requirements.txt --upgrade
```

make sure your version 2.02 and you can add collections to tv shows now.
