### ISSUE TITLE
show_missing movies by playlists instead of globally

### ISSUE THREAD

**Issue by hbooo** [pbrink231/plex_top_playlists#25]
Hi, 

show_missing is very useful to find which movies are missing from a playlist but in some case we can have a lot a missing movies and don't want to have all of them displayed in missing movies report.

When radarr will be plugged to this script it could lead to some problems if for example all movies from "10001 movies you must seen before you die" are added.

Add the possibility to choose for each playlist if we want to monitor the missing items or not will prevent this.

Hope you find this idea interesting

**Comment by pbrink231** [comment]
Sounds good.  

So a skip missing detail type of thing.  Won’t show them on the summary or discord and future not go to radarr?

**Comment by hbooo** [comment]
sounds perfect !

**Comment by pbrink231** [comment]
can add  "show_summary": "False" to any list item and it will show the small summary but not the detail and will ignore discord.

A few examples have them in the settings.ini.example file.

Fixed version 2.03

**Comment by hbooo** [comment]
Not sure if it's from this fix or the more than 100 items one but you leave some text tests (here) in the output I guess :) 

`count of imdb lists: 72
here here Studio Ghibli
here here
getting imdb ids from url: https://www.imdb.com/list/ls076439519/
Studio Ghibli: STARTING PLAYLIST - TYPE: custom - URL: https://www.imdb.com/list/ls076439519/ - KIND: collection
Studio Ghibli: finding matching movies for playlist with count 21

        21 of 21 found in imdb list:
            Studio Ghibli
        That means you are MISSING:
            0

    Not missing any
    
here here Oscar du meilleur film
here here
getting imdb ids from url:`

**Comment by pbrink231** [comment]
Need to fix that.  Opening till I clean it up

**Comment by pbrink231** [comment]
removed those extra "here here" from the outputs
