### ISSUE TITLE
Bad Trakt Code ( trakt.tv/users/xy/watchlist )

### ISSUE THREAD

**Issue by snickers2k** [pbrink231/plex_top_playlists#28]
```
STARTING TRAKT LIST - TYPE: popular - URL: https://trakt.tv/users/magicwashroom/watchlist?sort=popularity,asc - KIND: collection
Bad Trakt Code
```

sync from trakt-users-lists not working

**Comment by pbrink231** [comment]
you need to create a trakt code.

Instructions for making yourself a trakt app
https://github.com/pbrink231/plex_top_playlists/wiki/Trakt-token

**Comment by pbrink231** [comment]
Let me know if it is something else that is the problem

**Comment by snickers2k** [comment]
thank you.

hmm.. i have entered the trakt-api-key already.
is it only possible to get users own playlists?

"api-lists" like popular and trending works

**Comment by pbrink231** [comment]
Can you post your relevant settings file code here?

Checked the code and the reason for this is a failed api call which.  My guess is the settings file information is wrong somehow.  I need to clean up the error to return the actual error.

**Comment by pbrink231** [comment]
As for personal playlists from trakt, I believe I tested this a little while back but I will double check.

**Comment by pbrink231** [comment]
#26 I believe it relates to this.  I will try and fix it up soon.

**Comment by pbrink231** [comment]
#26

**Comment by pbrink231** [comment]
Going to close this.  Please comment into the other issue.  Started the discussion on the best way to deal with differences between trakt and plex lists
