### ISSUE TITLE
Is it possible to add other trakt lists?

### ISSUE THREAD

**Issue by dballard8** [pbrink231/plex_top_playlists#30]
I want to be able to add public trakt lists. If it has to be sone in collections, that is fine I just need to know how to add it to the settings file.

**Comment by Dex321x** [comment]
i'm interested in that too. I would like some custom user lists like [2020 Oscar Nominees](https://trakt.tv/users/andreofgyn/lists/2020-oscar-nominees-winners?sort=rank,asc)

**Comment by eltonzz** [comment]
Any luck with adding public trakt playlists?

**Comment by pbrink231** [comment]
I only am allowed what the trakt api allows.  I dont remember seeing public lists available but that was a while back.  Will check it out again.

**Comment by pbrink231** [comment]
On the develop branch you can now add trakt user lists.  These can be mixed with movies and shows.  They can be playlists or collections.

`git checkout develop` then run like normal

**Comment by pbrink231** [comment]
Original thread with this issue #26
