### ISSUE TITLE
Missing IMDB Ids not displayed in logs

### ISSUE THREAD

**Issue by hbooo** [pbrink231/plex_top_playlists#33]
Hi, 

I have my settings.ini file configured like this : 

`
### [OPTIONAL] Show the list of missing movies
# Set to True to see missing IMDB IDs from movie lists.  default is False
show_missing: True`

But nothing is displayed in log report
`here here Ocean's series
here here
getting imdb ids from url: https://www.imdb.com/list/ls068557644/
Ocean's series: STARTING PLAYLIST - TYPE: custom - URL: https://www.imdb.com/list/ls068557644/ - KIND: collection
Ocean's series: finding matching movies for playlist with count 4

4 of 4 found in imdb list:
Ocean's series
That means you are MISSING:
0
here here Eastrail 177
here here
getting imdb ids from url: https://www.imdb.com/list/ls021847110/
Eastrail 177: STARTING PLAYLIST - TYPE: custom - URL: https://www.imdb.com/list/ls021847110/ - KIND: collection
Eastrail 177: finding matching movies for playlist with count 3

1 of 3 found in imdb list:
Eastrail 177
That means you are MISSING:
2
here here Mission Impossible
here here
getting imdb ids from url: https://www.imdb.com/list/ls066600640/
Mission Impossible: STARTING PLAYLIST - TYPE: custom - URL: https://www.imdb.com/list/ls066600640/ - KIND: collection
Mission Impossible: finding matching movies for playlist with count 6

6 of 6 found in imdb list:
Mission Impossible
That means you are MISSING:
0
here here `

Also I have a lot of "here" text displayed that makes logs not easily readable.

I tried to set verbose:  to 1 and 3 with same result

**Comment by pbrink231** [comment]
I will check out the `here here` text.

I dont see a settings file but will try recreating from the log info here tomorrow

**Comment by pbrink231** [comment]
This should be better with the new develop branch.

you can try it out using `git checkout develop`.  Let me know if it solves it.  The new branch will always spit out missing IDs

**Comment by pbrink231** [comment]
I have pushed the develop branch into master.  This should no longer be an issue.  Please let me know if that is not the case.
