### ISSUE TITLE
IMDb - Festivals

### ISSUE THREAD

**Issue by danz1995** [pbrink231/plex_top_playlists#34]
First, thanks a lot for your program! It is pretty good and it has been helping a lot with my collection.

As a suggestion, do you think you can add support to links that are related to festivals? Those on IMDb are referred as events.

For instance:
https://www.imdb.com/event/ev0000235/2019/1
https://www.imdb.com/event/ev0000147/2019/1

Thanks in advance!

**Comment by pbrink231** [comment]
Checked out the links.  It looks like I can pull the tt id from `event-widgets__nominee-image` on the image link for each movie nominated in every category
What I am wondering what you want.  
Is just a list of all movies from the festival link work?

**Comment by danz1995** [comment]
> Checked out the links. It looks like I can pull the tt id from `event-widgets__nominee-image` on the image link for each movie nominated in every category
> What I am wondering what you want.
> Is just a list of all movies from the festival link work?

Hey, thanks for the follow up. I was able to do this! Created a SqLite file with movie, festival, category and win/lose. :)

**Comment by pbrink231** [comment]
Great to hear
