### ISSUE TITLE
Unable to scan plex libraries

### ISSUE THREAD

**Issue by zenjabba** [pbrink231/plex_top_playlists#36]
Using settings file
===================================================================
   Automated Playlist to Plex script
===================================================================

Retrieving a list of movies from the 'Movies' library in Plex...
The 'Movies' library does not exist in Plex.
Found 0 movies total in 'all movies' list from Plex...
Creating movie dictionary based on ID

cached plex movies
Retrieving new lists
count of imdb lists: 0
Retrieving a list of shows from the 'Tv Shows' library in Plex...
The 'Tv Shows' library does not exist in Plex.
Found 0 show total in 'all shows' list from Plex...

===================================================================
                               Done!
===================================================================

I've confirmed the details are all correct, but is there anyway to get the script to actually show me what errors it's seeing?

**Comment by ookla-ariel-ride** [comment]
I am having the same issue

**Comment by pbrink231** [comment]
Can you drop your settings file here so I can try it out.  I need to put better error handling in.

**Comment by ookla-ariel-ride** [comment]
@pbrink231, the code started working again and this error no longer comes up anymore for me.  Unsure if it is due to updating an underlying package or plexapi or ???.  I am having a new issue however, and will open a separate issue for the new problem.

**Comment by pbrink231** [comment]
Good to hear.
