### ISSUE TITLE
Endpoint or Type for trending Movies or Shows

### ISSUE THREAD

**Issue by FazzaDazza** [pbrink231/plex_top_playlists#39]
Hi

Im trying to add the trending movies to Plex and using the line below but this doesnt seem to work. 

`{ "title": "Trending Movies Test", "type":"trending", "limit": 80, "url":"https://api.trakt.tv/movies/trending", "kind":"collection"}`

I think it has to do with the type maybe something like movies.trending or movies/trending , just not sure. Please can you point me in the right direction.

**Comment by FazzaDazza** [comment]
Never mind, that seems more like an internal field, I just used "watched" and it worked

**Comment by pbrink231** [comment]
@FazzaDazza type really doesnt matter unless you are using popular list  So just set it to watched for everything except popular lists.  The new updates in develop are better and going to clear these up more.  This is due to popular lists returning different JSON than all the other lists.

**Comment by FazzaDazza** [comment]
@pbrink231 Awesome, thanks for fast response. Keen to see the new updates. Keep up the great work :)
