### ISSUE TITLE
issue with first run

### ISSUE THREAD

**Issue by brtbach** [pbrink231/plex_top_playlists#41]
`# python3 ./plex_playlist_update.py run
Traceback (most recent call last):
  File "./plex_playlist_update.py", line 19, in <module>
    import global_vars
  File "/usr/scripts/plex_top_playlists/global_vars.py", line 88
    print(f"SKIPPING SETTINGS LIST: Problem with trakt-movie-list, {ex}")
                                                                       ^
SyntaxError: invalid syntax`

Didnt touched the trakt-movie-list, used the plain from example settings

**Comment by brtbach** [comment]
I just tested the release version, which is working fine.

**Comment by brtbach** [comment]
I removed a bunch of print (f" and print(f' now it seems to work.

IMDB worked fine, trakt giving me 

PULLING LIST - Movies Top Weekly: URL: https://api.trakt.tv/movies/watched/weekly - TYPE: watched - KIND: playlist
ERROR: Bad Trakt Request: {ex}

**Comment by brtbach** [comment]
im stupid, if someone facing this issue: upgrade your system that you can use python3.6 or newer.

**Comment by pbrink231** [comment]
Hi brtbach.  Thanks for finding your issue.  I will see if there is a way
to test the version and give a better warning.
