### ISSUE TITLE
not working with python3: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by spuniun** [pbrink231/plex_top_playlists#5]
I was trying to test this neat idea out and came up with some varying behavior depending on python versions used. First, in order to get the script to work without module import error in Ubunutu 14 Python 3.4 I had to change the following lines:
```
+try:
+        from urllib.request import Request, urlopen
+except ImportError:
+        from urllib2 import Request, urlopen
-from urllib2 import Request, urlopen
```

However that still resulted in the following:
```
Retrieving a list of movies from the 'Movies' library in Plex...
Retrieving new lists
Retrieving the Trakt weekly list...
Traceback (most recent call last):
  File "plex_playlist_update.py", line 312, in <module>
    list_updater()
  File "plex_playlist_update.py", line 303, in list_updater
    run_movies_lists(plex)
  File "plex_playlist_update.py", line 266, in run_movies_lists
    trakt_weekly_imdb_ids = trakt_watched_imdb_id_list()
  File "plex_playlist_update.py", line 175, in trakt_watched_imdb_id_list
    trakt_movies = json.load(response)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by pbrink231** [comment]
Looking into python 3.6 from a windows setup now.  little slow with other work

**Comment by spuniun** [comment]
I have no problem using python2 but not sure if that timeout was on trakt end or script

**Comment by pbrink231** [comment]
This is only on python3?  Everytime?

**Comment by GertJanFrl** [comment]
Hi! Yes the problem is in Python 3! I've also changed the import on my end, and also get the "TypeError: the JSON object must be str, not 'bytes'"

**Comment by spuniun** [comment]
Yes python3 has that error. The 504 timeout must have been at trakt end because it's resolved now so I'll modify the issue title.

**Comment by pbrink231** [comment]
Not sure the reason for the previous issue but the new script is made for Python 3 specifically.  Should have no problem.
