### ISSUE TITLE
TV library getting zero matches with new Plex TV Agent

### ISSUE THREAD

**Issue by spuniun** [pbrink231/plex_top_playlists#52]
I hadn't used this script in a year or so and decided to dust it off and get it back in service.
Ran perfectly for all of my movie library and lists, but for my Trakt weekly top list it matched zero shows:
```
        0 of 20 found in list:
            Top Weekly Shows
        MISSING: 20
TVDB: 362696  |  TVDB: 412366  |  TVDB: 367146  |  TVDB: 341164
TVDB: 355730  |  TVDB: 328711  |  TVDB: 396390  |  TVDB: 280619
TVDB: 76733  |  TVDB: 73762  |  TVDB: 376837  |  TVDB: 314087
TVDB: 279121  |  TVDB: 386630  |  TVDB: 75805  |  TVDB: 341852
TVDB: 378023  |  TVDB: 399731  |  TVDB: 394924  |  TVDB: 75978
```
However, most of these are available in my library. It would seem that this tool cannot find the TVDb ID of shows when they are using the newest Plex TV Agent despite that value still being available from the API, albeit in a different location, and not as part of the guid:
```
<Guid id="tvdb://412366" />
```
Any chance we can get the TV matching logic updated for the new Plex TV Agent?

**Comment by mystardious** [comment]
Might be able to fix it with this:

https://github.com/pbrink231/plex_top_playlists/pull/50/commits/552d08f196429fa8ab6431d7ce662d923eaf3402

**Comment by pbrink231** [comment]
closing this issue as depricating this project.
I would check out plex-meta-manager.  Features similar but much better than this project.
