### ISSUE TITLE
Removal script

### ISSUE THREAD

**Issue by louis-lau** [pbrink231/plex_top_playlists#6]
Hey,
Not really an issue, you can mark it as an improvement :)
I ran the script once for all users realizing later that I wanted different names for the playlists, this means removing the first set of playlists. It's easy enough to comment out `plex.createPlaylist(playlist_name, list)` but a removal script would be a nice addition.

Thanks for the script,
Louis

**Comment by pbrink231** [comment]
I should be able to just copy some of the code and create a simple script.

**Comment by pbrink231** [comment]
I added a remove_only variable.

By setting this to true it will remove all created playlists.  Easy way of undoing.  It follows the same rules as adding lists so you can change them to remove from only certain user, all users or just the script runner.
