### ISSUE TITLE
Add support for other IMDb searches

### ISSUE THREAD

**Issue by spuniun** [pbrink231/plex_top_playlists#9]
I'm just loving your script. A couple things I may try to submit for you myself are to break the settings out to a config.ini so we don't have to stash them on updates, and I was thinking I'd try and add the ability to use other custom IMDb searches such as

http://www.imdb.com/search/title?count=250&groups=oscar_best_picture_winners&sort=year,desc&view=simple

I currently maintain a lot of these search groups manually with collections and your script has already removed the need for me to maintain the Top 250 and I'm eager to see where else I can automate some of my work.

If I figure it out well I'll submit for your approval. I'm thinking I can crib off your work enough to suss it out.

**Comment by pbrink231** [comment]
I was looking for a .env style but couldn't find it.  Ill look for a config file.  That will make it much easier.

For IMDB i have found 2 formats.  A top and a popular.  The top i have so if there is a list that looks like the top 250 it is 2 lines of code and add setup variables at the top. 

The popular i need to create.

This list ill check but might be the same as the top list

**Comment by spuniun** [comment]
I gave you a [pull request](https://github.com/pbrink231/plex_top_playlists/pull/10) to split out the settings file. It's working on my end. I guess I should have branched from development instead of master but, oh well - my first time contributing on github.

I will test the other imdb list format as well.

**Comment by pbrink231** [comment]
I made the settings.ini file now be an array so should be able to easily add any IMDb lists, charts or searches.
